feat(frontend): create login page
pwr-TeamProject23/M1 pull request #9
Opened 2023-10-09 10:21 UTC by jankrokos

2023-10-09 10:42 UTC, CreativePhilip requested changes

2023-10-09 10:42 UTC, CreativePhilip commented on rms_fe/src/index.css
> +}
This can be a css file local to the component, you can just import it inside the home page using the `import cssfile.css` syntax

2023-10-09 10:42 UTC, CreativePhilip commented on rms_fe/src/views/LoginPage.tsx
> +    remember?: string
We will allways remember the users so no need for this field

2023-10-09 10:42 UTC, CreativePhilip commented on rms_fe/src/views/LoginPage.tsx
> +                <Button type="text" icon={<LeftOutlined />} href="/" />
I don't think we need this button

2023-10-09 10:42 UTC, jsyska requested changes

2023-10-09 10:42 UTC, jsyska commented on rms_fe/src/views/LoginPage.tsx
> +                    name="basic"
maybe change name to 'login'

2023-10-12 13:45 UTC, jsyska approved these changes

2023-10-12 13:45 UTC, CreativePhilip approved these changes

2023-10-12 13:51 UTC, merged